// Handles references to all necessary DOM elements

export const elements = {
    loginView: document.getElementById('login-view'),
    dashboardView: document.getElementById('dashboard-view'),
    loginBtn: document.getElementById('login-btn'),
    logoutBtn: document.getElementById('logout-btn'),
    usernameInput: document.getElementById('username'),
    passwordInput: document.getElementById('password'),
    adminPanelBtn: document.getElementById('admin-panel-btn'),
    adminModal: document.getElementById('admin-modal'),
    closeAdminModal: document.getElementById('close-admin-modal'),
    clientModal: document.getElementById('client-modal'),
    closeClientModal: document.getElementById('close-client-modal'),
    accountModal: document.getElementById('account-modal'),
    closeAccountModal: document.getElementById('close-account-modal'),
    accountSelect: document.getElementById('account-select'),
    campaignSelect: document.getElementById('campaign-select'),
    adSelect: document.getElementById('ad-select'),
    startDateInput: document.getElementById('start-date'),
    endDateInput: document.getElementById('end-date'),
    fetchDataBtn: document.getElementById('fetch-data-btn'),
    amountSpentElement: document.getElementById('amount-spent'),
    messagesElement: document.getElementById('messages'),
    costPerResultElement: document.getElementById('cost-per-result'),
    reachElement: document.getElementById('reach'),
    impressionsElement: document.getElementById('impressions'),
    cpmElement: document.getElementById('cpm'),
    uniqueClicksElement: document.getElementById('unique-clicks'),
    uniqueCtrElement: document.getElementById('unique-ctr'),
    campaignsTableBody: document.getElementById('campaigns-table').querySelector('tbody'),
    clientsTableBody: document.getElementById('clients-table'),
    accountsTableBody: document.getElementById('accounts-table'),
    clientSelectAdmin: document.getElementById('client-select'),
    accountClientSelectAdmin: document.getElementById('account-client-select'),
    apiKeyTextareaAdmin: document.getElementById('api-key'),
    saveApiBtnAdmin: document.getElementById('save-api-btn'),
    addClientBtnAdmin: document.getElementById('add-client-btn'),
    addAccountBtnAdmin: document.getElementById('add-account-btn'),
    saveClientBtn: document.getElementById('save-client-btn'),
    saveAccountBtn: document.getElementById('save-account-btn'),
    clientNameInputModal: document.getElementById('client-name'),
    clientPasswordInputModal: document.getElementById('client-password'),
    accountNameInputModal: document.getElementById('account-name'),
    accountIdInputModal: document.getElementById('account-id-input'),
    clientIdInputModal: document.getElementById('client-id'),
    accountIdHiddenInputModal: document.getElementById('account-id'),
    clientModalTitle: document.getElementById('client-modal-title'),
    accountModalTitle: document.getElementById('account-modal-title'),
    adminTabs: document.querySelectorAll('.modal-content .tab-btn'), // Use modal-content scope
    adminTabContents: document.querySelectorAll('.modal-content .tab-content'), // Use modal-content scope
    metricsChartCanvas: document.getElementById('metrics-chart')
};

